package org.atomium.metadata;

import org.atomium.Ref;
import org.atomium.SimpleRef;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * @author Blackrush
 */
public abstract class ColumnMetadata<T> implements ColumnInfo {
    private final Metadata<T> parent;
    private final String name;

    public ColumnMetadata(Metadata<T> parent, String name) {
        this.parent = checkNotNull(parent);
        this.name = checkNotNull(name);
    }

    /**
     * get the {@link Metadata} that owns this column
     * @return the non-null parent
     */
    public Metadata<T> getParent() {
        return parent;
    }

    /**
     * get the {@link org.atomium.metadata.MetadataRegistry} that contains this column's parent
     * @return the non-null parent's registry
     */
    public MetadataRegistry getRegistry() {
        return parent.getRegistry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return name;
    }

    /**
     * get the {@link ConverterInterface} that can handle this column
     * @return a nullable {@link ConverterInterface}
     */
    public ConverterInterface getConverter() {
        return getRegistry().getConverterFor(getTarget());
    }

    /**
     * do some back-end operations
     */
    public abstract void load();

    /**
     * gets column's value of the given instance
     * @param instance the non-null instance
     * @return the nullable value
     */
    public abstract Object get(T instance);

    /**
     * sets column's value of the given instance
     * @param instance the non-null instance
     * @param o the nullable value
     */
    public abstract void set(T instance, Object o);

    /**
     * creates a new {@link Ref} bound to this column with the given identifier
     * @param identifier the identifier
     * @return a non-null {@link Ref}
     */
    public Ref<T> getRef(Object identifier) {
        return new SimpleRef<>(this, identifier);
    }

    @Override
    public ColumnInfo asColumnInfo() {
        return SimpleColumnInfo.create(getName(), getTarget(), isPrimaryKey(), isAutogenerated(), isNullable());
    }
}
