package org.atomium.metadata;

import com.google.common.reflect.TypeToken;

/**
 * @author Blackrush
 */
public interface ColumnInfo {
    /**
     * get this column's name
     * @return the non-null name
     */
    String getName();

    /**
     * get this column's target type
     * @return the non-null target
     */
    TypeToken<?> getTarget();

    /**
     * returns <code>true</code> if this column is a primary key, <code>false</code> otherwise
     * @return <code>true</code> if this column is a primary key, <code>false</code> otherwise
     */
    boolean isPrimaryKey();

    /**
     * returns <code>true</code> if this column is autogenerated, <code>false</code> otherwise
     * @return <code>true</code> if this column is autogenerated, <code>false</code> otherwise
     */
    boolean isAutogenerated();

    /**
     * returns <code>true</code> if this column is nullable, <code>false</code> otherwise
     * @return <code>true</code> if this column is nullable, <code>false</code> otherwise
     */
    boolean isNullable();

    ColumnInfo withName(String name);
    ColumnInfo withTarget(TypeToken<?> target);
    ColumnInfo withPrimaryKey(boolean primaryKey);
    ColumnInfo withAutogenerated(boolean autogenerated);
    ColumnInfo withNullable(boolean nullable);

    ColumnInfo asColumnInfo();
}
