package org.atomium.metadata;

import org.atomium.Ref;
import org.atomium.SimpleRef;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * @author Blackrush
 */
public abstract class ColumnMetadata<T> implements ColumnInfo {
    private final Metadata<T> parent;
    private final String name;

    public ColumnMetadata(Metadata<T> parent, String name) {
        this.parent = checkNotNull(parent);
        this.name = checkNotNull(name);
    }

    /**
     * get the {@link Metadata} that owns this column
     * @return the non-null parent
     */
    public Metadata<T> getParent() {
        return parent;
    }

    /**
     * get the {@link org.atomium.metadata.MetadataRegistry} that contains this column's parent
     * @return the non-null parent's registry
     */
    public MetadataRegistry getRegistry() {
        return parent.getRegistry();
    }

    @Override
    public String getName() {
        return name;
    }

    public ConverterInterface getConverter() {
        return getRegistry().getConverterFor(getTarget());
    }

    public abstract void load();

    public abstract Object get(T entity);
    public abstract void set(T entity, Object o);

    public Ref<T> getRef(Object identifier) {
        return new SimpleRef<>(this, identifier);
    }

    @Override
    public ColumnInfo asColumnInfo() {
        return SimpleColumnInfo.create(getName(), getTarget(), isPrimaryKey(), isAutogenerated(), isNullable());
    }
}
