package org.atomium.metadata;

import com.google.common.reflect.TypeToken;
import org.atomium.annotations.Column;
import org.atomium.annotations.PrimaryKey;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import static com.google.common.base.Throwables.propagate;

/**
 * @author Blackrush
 */
public class PropertyColumnMetadata<T> extends ColumnMetadata<T> {
    private final Method getter, setter;

    private boolean primaryKey, autogenerated, nullable;

    public PropertyColumnMetadata(Metadata<T> parent, String name, Method getter, Method setter) {
        super(parent, name);
        this.getter = getter;
        this.setter = setter;
    }

    @Override
    public Object get(T instance) {
        try {
            return getter.invoke(instance);
        } catch (IllegalAccessException e) {
            throw propagate(e);
        } catch (InvocationTargetException e) {
            throw propagate(e.getTargetException());
        }
    }

    @Override
    public void set(T instance, Object o) {
        try {
            setter.invoke(instance, o);
        } catch (IllegalAccessException e) {
            throw propagate(e);
        } catch (InvocationTargetException e) {
            throw propagate(e.getTargetException());
        }
    }

    @Override
    public void load() {
        nullable = getter.getAnnotation(Column.class).nullable();

        PrimaryKey pkey = getter.getAnnotation(PrimaryKey.class);
        if (pkey != null) {
            primaryKey = true;
            autogenerated = pkey.autogenerated();
            nullable = false;
        }
    }

    @Override
    public TypeToken<?> getTarget() {
        return TypeToken.of(getter.getGenericReturnType());
    }

    @Override
    public boolean isPrimaryKey() {
        return primaryKey;
    }

    @Override
    public boolean isAutogenerated() {
        return autogenerated;
    }

    @Override
    public boolean isNullable() {
        return nullable;
    }

    @Override
    public ColumnInfo withName(String name) {
        return SimpleColumnInfo.create(name, getTarget(), primaryKey, autogenerated, nullable);
    }

    @Override
    public ColumnInfo withTarget(TypeToken<?> target) {
        return SimpleColumnInfo.create(getName(), target, primaryKey, autogenerated, nullable);
    }

    @Override
    public ColumnInfo withPrimaryKey(boolean primaryKey) {
        return SimpleColumnInfo.create(getName(), getTarget(), primaryKey, autogenerated, nullable);
    }

    @Override
    public ColumnInfo withAutogenerated(boolean autogenerated) {
        return SimpleColumnInfo.create(getName(), getTarget(), primaryKey, autogenerated, nullable);
    }

    @Override
    public ColumnInfo withNullable(boolean nullable) {
        return SimpleColumnInfo.create(getName(), getTarget(), primaryKey, autogenerated, nullable);
    }
}
